def code

pipeline {
    node {
        def code1 = load 'example.groovy'
        code1.example1()
    }
    agent any
    stages {
        stage('Load'){
            steps {
                sh 'not working'
            }
        }
        stage('Execute'){
            steps {
                 sh 'not working'
            }
        }
    }
}