def code

pipeline {
    agent any
    stages {
        stage('Load'){
            steps {
                script {
                    code = load('include-groovy/example.groovy')
                    code.example1()
                }
            }
        }
        stage('Execute'){
            steps {
                script {
                    code.example1()
                }
            }
        }
    }
}