def code

pipeline {
    agent any
    stages {
        stage('Load'){
            script {
                code = load 'example.groovy'
            }
        }
        stage('Execute'){
            script {
                code.example1()
            }
        }
    }
}